data_dir: ./data
results_dir: ./results

mapping: {}
clustering:
  eps: 0.5
  min_samples: 5
gsea:
  output_dir: ./results/gsea
ml:
  model: random_forest
  n_estimators: 200
logodds: {}
prioritization: {}
drug_id: {}
permutation:
  n_iter: 1000
